### ISSUE TITLE
Code Style step at Compass Github Actions doesn't work with forked branches

### ISSUE THREAD

**Issue by pedromcborges** [ZupIT/charlescd#978]
**Describe the bug**
This step exists in Compass and is about to exist in Hermes and Gate as well, to check the code style:

```
- name: Code Style
        uses: docker://morphy/revive-action:v1
        with:
          config: ./compass/revive.toml
          path: "./compass/..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

When opening a PR from a fork I realized that this step was breaking.
This GITHUB_TOKEN is the problem, when trying to take the fork branch, the step breaks, because it does not have access to the key.

**To Reproduce**
1. Create a fork of ZupIT/charlescd
2. Make a change at Compass module.
3. Commit, push and open a Pull Request
4. Wait Github actions to run
5. See error
